Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder "./confs", "/home/vagrant/confs"
    config.vm.network "forwarded_port", guest: 80, host: 8080  # HTTP
    config.vm.network "forwarded_port", guest: 443, host: 8443 # HTTPS
    
    config.vm.define "lcamerlyS" do |master|
      master.vm.hostname = "lcamerlyS"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      master.vm.provision "shell", path: "./scripts/server.sh"
    end

  end
